### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Drizzt-IT** [BSData/dropzone-commander#5]
I would like to maintain the files.

**Comment by amis92** [comment]
Hello, @Drizzt-IT. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Cheers!

[invitation]: https://github.com/BSData/dropzone-commander/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
